version: 2

general:
  branches:
    only:
      - master
      - test
      - dev
      # - /*/ # feature branches

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy_hlf_vm:
          filters:
            branches:
              only:
               - dev
               - test
               - master

jobs:

  deploy_hlf_vm:
      docker:
        - image: alpine
      working_directory: /app
      steps:
        - checkout
        - run:
            name: Install dependencies
            command: |
              apk update
              apk add git
              apk add --no-cache openssh rsync
        - run:
            name: Run deploy script
            command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                EC2_ENDPOINT=$EC2_ENDPOINT_master
              elif [ "${CIRCLE_BRANCH}" == "test" ]; then
                EC2_ENDPOINT=$EC2_ENDPOINT_test
              elif [ "${CIRCLE_BRANCH}" == "dev" ]; then
                EC2_ENDPOINT=$EC2_ENDPOINT_dev
              else
                exit 1;
              fi

              ssh -oStrictHostKeyChecking=no ubuntu@${EC2_ENDPOINT} 'bash -s' < ./.circleci/clean-hlf.sh;

              ssh -oStrictHostKeyChecking=no ubuntu@${EC2_ENDPOINT} '[ -d ~/HLF ] || mkdir ~/HLF';

              scp -oStrictHostKeyChecking=no -r . ubuntu@${EC2_ENDPOINT}:~/HLF;


              #scp -oStrictHostKeyChecking=no ./scripts/startFabric.sh ubuntu@${EC2_ENDPOINT}:~/;
              #scp -oStrictHostKeyChecking=no -r ./basic-network ubuntu@${EC2_ENDPOINT}:~/;
              #scp -oStrictHostKeyChecking=no -r ./chaincode/node ubuntu@${EC2_ENDPOINT}:~/;


              ssh -oStrictHostKeyChecking=no ubuntu@${EC2_ENDPOINT} 'chmod +x ~/HLF/scripts/startFabric.sh';
              ssh -oStrictHostKeyChecking=no ubuntu@${EC2_ENDPOINT} 'bash -s' < ./.circleci/deploy-hlf.sh;

